### ISSUE TITLE
Эпик Каталог (Поляков)

### ISSUE THREAD

**Issue by artwist-polyakov** [artwist-polyakov/iOS-FakeNFT-StarterProject-Public#2]
- [x] [Репозиторий каталога NFT  (10 часов)](https://github.com/artwist-polyakov/iOS-FakeNFT-StarterProject-Public/issues/4)
- [x] [Сортировки для  каталога NFT (2 часа)](https://github.com/artwist-polyakov/iOS-FakeNFT-StarterProject-Public/issues/5)
- [x] [Вёрстка каталога для работы с локальным слоем данных (12 часов)](https://github.com/artwist-polyakov/iOS-FakeNFT-StarterProject-Public/issues/6)
- [x] [Вёрстка страницы отдельной коллекции (12 часов)](https://github.com/artwist-polyakov/iOS-FakeNFT-StarterProject-Public/issues/7)
- [x] [Вёрстка страницы просмотра отдельной NFT (12 часов)](https://github.com/artwist-polyakov/iOS-FakeNFT-StarterProject-Public/issues/8)
- [x] Ожидаем реализации вебвью и подключение вебвью к стрпанице отдельной коллекции.
